// Generated by scripts/gen_achievements.py from Misskey 2026.9.1. Do not edit.

extension Achievement {
    static let catalog: [String: Achievement] = [
        "notes1": Achievement(
            title: "just setting up my msky",
            description: "初めてノートを投稿した",
            flavor: "良いMisskeyライフを！",
            emoji: "1f4dd", background: (0x3bbb74, 0xc7d366), frame: .bronze),
        "notes10": Achievement(
            title: "いくつかのノート",
            description: "ノートを10回投稿した",
            flavor: nil,
            emoji: "1f4d1", background: nil, frame: .bronze),
        "notes100": Achievement(
            title: "たくさんのノート",
            description: "ノートを100回投稿した",
            flavor: nil,
            emoji: "1f4d2", background: (0x3bbb74, 0xc7d366), frame: .bronze),
        "notes500": Achievement(
            title: "ノートまみれ",
            description: "ノートを500回投稿した",
            flavor: nil,
            emoji: "1f4da", background: nil, frame: .bronze),
        "notes1000": Achievement(
            title: "ノートの山",
            description: "ノートを1,000回投稿した",
            flavor: nil,
            emoji: "1f5c3", background: (0x3bbb74, 0xc7d366), frame: .bronze),
        "notes5000": Achievement(
            title: "湧き出るノート",
            description: "ノートを5,000回投稿した",
            flavor: nil,
            emoji: "1f304", background: (0x3bbb74, 0xc7d366), frame: .bronze),
        "notes10000": Achievement(
            title: "スーパーノート",
            description: "ノートを10,000回投稿した",
            flavor: nil,
            emoji: "1f3d9", background: (0xdcdfe1, 0xacc0cf), frame: .silver),
        "notes20000": Achievement(
            title: "ニードモアノート",
            description: "ノートを20,000回投稿した",
            flavor: nil,
            emoji: "1f307", background: (0xdcdfe1, 0xacc0cf), frame: .silver),
        "notes30000": Achievement(
            title: "ノートノートノート",
            description: "ノートを30,000回投稿した",
            flavor: nil,
            emoji: "1f306", background: (0x90e0ff, 0xffa8fc), frame: .silver),
        "notes40000": Achievement(
            title: "ノート工場",
            description: "ノートを40,000回投稿した",
            flavor: nil,
            emoji: "1f303", background: (0xc545c0, 0x02709b), frame: .silver),
        "notes50000": Achievement(
            title: "ノートの惑星",
            description: "ノートを50,000回投稿した",
            flavor: nil,
            emoji: "1fa90", background: (0x90e0ff, 0xffa8fc), frame: .gold),
        "notes60000": Achievement(
            title: "ノートクエーサー",
            description: "ノートを60,000回投稿した",
            flavor: nil,
            emoji: "2604", background: (0xc545c0, 0x02709b), frame: .gold),
        "notes70000": Achievement(
            title: "ブラックノートホール",
            description: "ノートを70,000回投稿した",
            flavor: nil,
            emoji: "1f30c", background: (0x90e0ff, 0xffa8fc), frame: .gold),
        "notes80000": Achievement(
            title: "ノートギャラクシー",
            description: "ノートを80,000回投稿した",
            flavor: nil,
            emoji: "1f30c", background: (0xc545c0, 0x02709b), frame: .gold),
        "notes90000": Achievement(
            title: "ノートバース",
            description: "ノートを90,000回投稿した",
            flavor: nil,
            emoji: "1f30c", background: (0xffe877, 0xff8c29), frame: .gold),
        "notes100000": Achievement(
            title: "ALL YOUR NOTE ARE BELONG TO US",
            description: "ノートを100,000回投稿した",
            flavor: "そんなに書くことある？",
            emoji: "267e", background: (0xffe877, 0xff8c29), frame: .platinum),
        "login3": Achievement(
            title: "ビギナーⅠ",
            description: "通算ログイン日数が3日",
            flavor: "今日からね僕は ミスキストってことで",
            emoji: "1f331", background: nil, frame: .bronze),
        "login7": Achievement(
            title: "ビギナーⅡ",
            description: "通算ログイン日数が7日",
            flavor: "慣れてきましたか？",
            emoji: "1f331", background: (0x3bbb74, 0xc7d366), frame: .bronze),
        "login15": Achievement(
            title: "ビギナーⅢ",
            description: "通算ログイン日数が15日",
            flavor: nil,
            emoji: "1f331", background: (0x90e0ff, 0xffa8fc), frame: .bronze),
        "login30": Achievement(
            title: "ミスキストⅠ",
            description: "通算ログイン日数が30日",
            flavor: nil,
            emoji: "1fab4", background: nil, frame: .bronze),
        "login60": Achievement(
            title: "ミスキストⅡ",
            description: "通算ログイン日数が60日",
            flavor: nil,
            emoji: "1fab4", background: (0x3bbb74, 0xc7d366), frame: .bronze),
        "login100": Achievement(
            title: "ミスキストⅢ",
            description: "通算ログイン日数が100日",
            flavor: "そのユーザー、ミスキストにつき",
            emoji: "1fab4", background: (0x90e0ff, 0xffa8fc), frame: .silver),
        "login200": Achievement(
            title: "常連Ⅰ",
            description: "通算ログイン日数が200日",
            flavor: nil,
            emoji: "1f333", background: nil, frame: .silver),
        "login300": Achievement(
            title: "常連Ⅱ",
            description: "通算ログイン日数が300日",
            flavor: nil,
            emoji: "1f333", background: (0x3bbb74, 0xc7d366), frame: .silver),
        "login400": Achievement(
            title: "常連Ⅲ",
            description: "通算ログイン日数が400日",
            flavor: nil,
            emoji: "1f333", background: (0x90e0ff, 0xffa8fc), frame: .silver),
        "login500": Achievement(
            title: "ベテランⅠ",
            description: "通算ログイン日数が500日",
            flavor: "諸君、私はノートが好きだ",
            emoji: "1f304", background: nil, frame: .silver),
        "login600": Achievement(
            title: "ベテランⅡ",
            description: "通算ログイン日数が600日",
            flavor: nil,
            emoji: "1f304", background: (0x3bbb74, 0xc7d366), frame: .gold),
        "login700": Achievement(
            title: "ベテランⅢ",
            description: "通算ログイン日数が700日",
            flavor: nil,
            emoji: "1f304", background: (0x90e0ff, 0xffa8fc), frame: .gold),
        "login800": Achievement(
            title: "ノートマスターⅠ",
            description: "通算ログイン日数が800日",
            flavor: nil,
            emoji: "1f307", background: nil, frame: .gold),
        "login900": Achievement(
            title: "ノートマスターⅡ",
            description: "通算ログイン日数が900日",
            flavor: nil,
            emoji: "1f307", background: (0x3bbb74, 0xc7d366), frame: .gold),
        "login1000": Achievement(
            title: "ノートマスターⅢ",
            description: "通算ログイン日数が1,000日",
            flavor: "Misskeyを使ってくれてありがとう！",
            emoji: "1f307", background: (0x90e0ff, 0xffa8fc), frame: .platinum),
        "passedSinceAccountCreated1": Achievement(
            title: "一周年",
            description: "アカウント作成から1年経過した",
            flavor: nil,
            emoji: "31-20e3", background: nil, frame: .bronze),
        "passedSinceAccountCreated2": Achievement(
            title: "二周年",
            description: "アカウント作成から2年経過した",
            flavor: nil,
            emoji: "32-20e3", background: nil, frame: .silver),
        "passedSinceAccountCreated3": Achievement(
            title: "三周年",
            description: "アカウント作成から3年経過した",
            flavor: nil,
            emoji: "33-20e3", background: nil, frame: .gold),
        "loggedInOnBirthday": Achievement(
            title: "ハッピーバースデー",
            description: "誕生日にログインした",
            flavor: nil,
            emoji: "1f382", background: (0xff4d4d, 0xf79bd6), frame: .silver),
        "loggedInOnNewYearsDay": Achievement(
            title: "あけましておめでとうございます",
            description: "元日にログインした",
            flavor: "今年も弊サーバーをよろしくお願いします",
            emoji: "1f38d", background: (0xff9090, 0xffe8a8), frame: .silver),
        "noteClipped1": Achievement(
            title: "クリップせずにはいられないな",
            description: "初めてノートをクリップした",
            flavor: nil,
            emoji: "1f587", background: nil, frame: .bronze),
        "noteFavorited1": Achievement(
            title: "星をみるひと",
            description: "初めてノートをお気に入りに登録した",
            flavor: nil,
            emoji: "1f31f", background: nil, frame: .bronze),
        "myNoteFavorited1": Achievement(
            title: "星が欲しい",
            description: "自分のノートが他の人からお気に入りに登録された",
            flavor: nil,
            emoji: "1f320", background: nil, frame: .silver),
        "profileFilled": Achievement(
            title: "準備万端",
            description: "プロフィール設定を行った",
            flavor: nil,
            emoji: "1f44c", background: (0xbbb73b, 0xff8f4d), frame: .bronze),
        "markedAsCat": Achievement(
            title: "吾輩は猫である",
            description: "アカウントをCatとして設定した",
            flavor: "名前はまだない。",
            emoji: "1f408", background: (0xbbb73b, 0xff8f4d), frame: .bronze),
        "following1": Achievement(
            title: "はじめてのフォロー",
            description: "初めてフォローした",
            flavor: nil,
            emoji: "2618", background: (0x3bbb74, 0xc7d366), frame: .bronze),
        "following10": Achievement(
            title: "ついてく、ついてく",
            description: "フォローが10人を超した",
            flavor: nil,
            emoji: "1f6b8", background: (0x3bbb74, 0xc7d366), frame: .bronze),
        "following50": Achievement(
            title: "友達たくさん",
            description: "フォローが50人を超した",
            flavor: nil,
            emoji: "1f91d", background: (0x3bbb74, 0xc7d366), frame: .bronze),
        "following100": Achievement(
            title: "友達100人",
            description: "フォローが100人を超した",
            flavor: nil,
            emoji: "1f4af", background: (0xff35b8, 0xffce45), frame: .silver),
        "following300": Achievement(
            title: "友達過多",
            description: "フォローが300人を超した",
            flavor: nil,
            emoji: "1f970", background: (0x90e0ff, 0xffa8fc), frame: .silver),
        "followers1": Achievement(
            title: "はじめてのフォロワー",
            description: "初めてフォローされた",
            flavor: nil,
            emoji: "2618", background: (0x3bbb74, 0xc7d366), frame: .bronze),
        "followers10": Achievement(
            title: "フォローミー！",
            description: "フォロワーが10人を超した",
            flavor: nil,
            emoji: "1f44b", background: (0x3bbb74, 0xc7d366), frame: .bronze),
        "followers50": Achievement(
            title: "ぞろぞろ",
            description: "フォロワーが50人を超した",
            flavor: nil,
            emoji: "1f411", background: (0xdcdfe1, 0xacc0cf), frame: .bronze),
        "followers100": Achievement(
            title: "人気者",
            description: "フォロワーが100人を超した",
            flavor: nil,
            emoji: "1f60e", background: (0x90e0ff, 0xffa8fc), frame: .silver),
        "followers300": Achievement(
            title: "一列でお並びください",
            description: "フォロワーが300人を超した",
            flavor: nil,
            emoji: "1f3c6", background: (0x90e0ff, 0xffa8fc), frame: .silver),
        "followers500": Achievement(
            title: "基地局",
            description: "フォロワーが500人を超した",
            flavor: nil,
            emoji: "1f4e1", background: (0xdcdfe1, 0xacc0cf), frame: .gold),
        "followers1000": Achievement(
            title: "インフルエンサー",
            description: "フォロワーが1,000人を超した",
            flavor: nil,
            emoji: "1f451", background: (0xffe877, 0xff8c29), frame: .platinum),
        "collectAchievements30": Achievement(
            title: "実績コレクター",
            description: "実績を30個以上獲得した",
            flavor: nil,
            emoji: "1f3c5", background: (0xff4d4d, 0xf79bd6), frame: .silver),
        "viewAchievements3min": Achievement(
            title: "実績好き",
            description: "実績一覧を3分以上眺め続けた",
            flavor: nil,
            emoji: "1f3c5", background: (0x90e0ff, 0xffa8fc), frame: .bronze),
        "iLoveMisskey": Achievement(
            title: "I Love Misskey",
            description: "\"I ❤ #Misskey\"を投稿した",
            flavor: "Misskeyを使ってくださりありがとうございます！ by 開発チーム",
            emoji: "2764", background: (0xff4d4d, 0xf79bd6), frame: .silver),
        "foundTreasure": Achievement(
            title: "宝探し",
            description: "隠されたお宝を発見した",
            flavor: nil,
            emoji: "1f3c6", background: (0xc545c0, 0x02709b), frame: .gold),
        "client30min": Achievement(
            title: "ひとやすみ",
            description: "クライアントを起動してから30分以上経過した",
            flavor: nil,
            emoji: "1f552", background: (0xdcdfe1, 0xacc0cf), frame: .bronze),
        "client60min": Achievement(
            title: "Misskeyの見すぎ",
            description: "クライアントを起動してから60分以上経過した",
            flavor: nil,
            emoji: "1f552", background: (0xdcdfe1, 0xacc0cf), frame: .silver),
        "noteDeletedWithin1min": Achievement(
            title: "いまのなし",
            description: "投稿してから1分以内にその投稿を削除した",
            flavor: nil,
            emoji: "1f5d1", background: (0xdcdfe1, 0xacc0cf), frame: .bronze),
        "postedAtLateNight": Achievement(
            title: "夜行性",
            description: "深夜にノートを投稿した",
            flavor: "そろそろ寝よう。",
            emoji: "1f319", background: (0xc545c0, 0x02709b), frame: .bronze),
        "postedAt0min0sec": Achievement(
            title: "時報",
            description: "0分0秒にノートを投稿した",
            flavor: "ポッ ポッ ポッ ピーン",
            emoji: "1f55b", background: (0x3ae7c6, 0x25c2ff), frame: .bronze),
        "selfQuote": Achievement(
            title: "自己言及",
            description: "自分のノートを引用した",
            flavor: nil,
            emoji: "1f4dd", background: nil, frame: .bronze),
        "htl20npm": Achievement(
            title: "流れるTL",
            description: "ホームタイムラインの流速が20npmを越す",
            flavor: nil,
            emoji: "1f30a", background: (0xdcdfe1, 0xacc0cf), frame: .bronze),
        "viewInstanceChart": Achievement(
            title: "アナリスト",
            description: "サーバーのチャートを表示した",
            flavor: nil,
            emoji: "1f4ca", background: (0x3ae7c6, 0x25c2ff), frame: .bronze),
        "outputHelloWorldOnScratchpad": Achievement(
            title: "Hello, world!",
            description: "スクラッチパッドで hello world を出力した",
            flavor: nil,
            emoji: "1f530", background: (0x3ae7c6, 0x25c2ff), frame: .bronze),
        "open3windows": Achievement(
            title: "マルチウィンドウ",
            description: "ウィンドウを3つ以上開いた状態にした",
            flavor: nil,
            emoji: "1f5a5", background: (0x90e0ff, 0xffa8fc), frame: .bronze),
        "driveFolderCircularReference": Achievement(
            title: "循環参照",
            description: "ドライブのフォルダを再帰的な入れ子にしようとした",
            flavor: nil,
            emoji: "1f4c2", background: (0x90e0ff, 0xffa8fc), frame: .bronze),
        "reactWithoutRead": Achievement(
            title: "ちゃんと読んだ？",
            description: "100文字以上のテキストを含むノートに投稿されてから3秒以内にリアクションした",
            flavor: nil,
            emoji: "2753", background: (0x90e0ff, 0xffa8fc), frame: .bronze),
        "clickedClickHere": Achievement(
            title: "ここをクリック",
            description: "ここをクリックした",
            flavor: nil,
            emoji: "2757", background: (0x90e0ff, 0xffa8fc), frame: .bronze),
        "justPlainLucky": Achievement(
            title: "単なるラッキー",
            description: "10秒ごとに0.005%の確率で獲得",
            flavor: nil,
            emoji: "1f340", background: (0xbbb73b, 0xff8f4d), frame: .silver),
        "setNameToSyuilo": Achievement(
            title: "神様コンプレックス",
            description: "名前を syuilo に設定した",
            flavor: nil,
            emoji: "1f36e", background: (0xbbb73b, 0xff8f4d), frame: .bronze),
        "cookieClicked": Achievement(
            title: "クッキーをクリックするゲーム",
            description: "クッキーをクリックした",
            flavor: "ソフト間違ってない？",
            emoji: "1f36a", background: (0xbbb73b, 0xff8f4d), frame: .bronze),
        "brainDiver": Achievement(
            title: "Brain Diver",
            description: "Brain Diverへのリンクを投稿した",
            flavor: "Misskey-Misskey La-Tu-Ma",
            emoji: "1f9e0", background: (0x90e0ff, 0xffa8fc), frame: .bronze),
        "smashTestNotificationButton": Achievement(
            title: "テスト過剰",
            description: "通知のテストをごく短時間のうちに連続して行った",
            flavor: nil,
            emoji: "1f514", background: (0xbbb73b, 0xff8f4d), frame: .bronze),
        "tutorialCompleted": Achievement(
            title: "Misskey初心者講座 修了証",
            description: "チュートリアルを完了した",
            flavor: nil,
            emoji: "1f393", background: (0xdcdfe1, 0xacc0cf), frame: .bronze),
        "bubbleGameExplodingHead": Achievement(
            title: "🤯",
            description: "バブルゲームで最も大きいモノを出した",
            flavor: nil,
            emoji: "1f92f", background: (0xff4d4d, 0xf79bd6), frame: .bronze),
        "bubbleGameDoubleExplodingHead": Achievement(
            title: "ダブル🤯",
            description: "バブルゲームで最も大きいモノを2つ同時に出した",
            flavor: "これくらいの　おべんとばこに　🤯　🤯　ちょっとつめて",
            emoji: "1f92f", background: (0xff4d4d, 0xf79bd6), frame: .silver),
    ]
}
