#!/usr/bin/env python3
"""Generates hibari/Model/AchievementCatalog.swift from Misskey's source.

The achievements Misskey itself defines: their Japanese title, description and flavor
(locales/ja-JP.yml) and their badge (packages/frontend/src/utility/achievements.ts).
Achievements a server adds on its own are not in it; the app shows their id.

    scripts/gen_achievements.py                    # from the local Misskey (scripts/local_misskey.py up)
    scripts/gen_achievements.py --misskey ~/misskey  # from a checkout
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "hibari/Model/AchievementCatalog.swift"
CONTAINER = "hibari-misskey-web-1"
BADGES = "packages/frontend/src/utility/achievements.ts"
LOCALE = "locales/ja-JP.yml"


def read_source(misskey: Path | None, path: str) -> str:
    if misskey:
        return (misskey / path).read_text(encoding="utf-8")
    return subprocess.run(["docker", "exec", CONTAINER, "cat", f"/misskey/{path}"],
                          check=True, capture_output=True, text=True).stdout


def parse_badges(source: str) -> dict:
    types = re.search(r"export const ACHIEVEMENT_TYPES = \[(.*?)\] as const", source, re.S)
    ids = re.findall(r"'(\w+)'", types.group(1))
    badges = {}
    for match in re.finditer(r"'(\w+)': \{\s*img: '/fluent-emoji/([0-9a-f-]+)\.png',\s*bg: (null|'[^']*'),"
                             r"\s*frame: '(\w+)',\s*\}", source):
        name, emoji, bg, frame = match.groups()
        background = None
        if bg != "null":
            colors = re.findall(r"rgb\((\d+),? (\d+),? (\d+)\)", bg)
            if not bg.startswith("'linear-gradient(0deg,") or len(colors) != 2:
                sys.exit(f"{name}: unsupported background {bg}")
            background = ["0x%02x%02x%02x" % tuple(int(c) for c in color) for color in colors]
        badges[name] = {"emoji": emoji, "background": background, "frame": frame}
    missing = [name for name in ids if name not in badges]
    if missing:
        sys.exit(f"no badge for {missing}")
    return {name: badges[name] for name in ids}


def parse_texts(source: str) -> dict:
    """`_achievements._types` of the locale: `_<id>:` then `title:` etc., each a quoted string."""
    lines = source.splitlines()
    start = lines.index("_achievements:")
    texts = {}
    in_types = False
    current = None
    for line in lines[start + 1:]:
        if line and not line.startswith(" "):
            break
        if line == "  _types:":
            in_types = True
            continue
        if not in_types:
            continue
        if re.fullmatch(r"  \S.*", line):
            break
        if match := re.fullmatch(r"    _(\w+):", line):
            current = texts.setdefault(match.group(1), {})
        elif match := re.fullmatch(r'      (\w+): ("(?:[^"\\]|\\.)*")', line):
            current[match.group(1)] = json.loads(match.group(2))
        elif line.strip():
            sys.exit(f"unexpected line in the locale: {line}")
    return texts


def swift_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--misskey", type=Path, help="a Misskey checkout (default: the local Misskey's container)")
    args = parser.parse_args()

    version = json.loads(read_source(args.misskey, "package.json"))["version"]
    badges = parse_badges(read_source(args.misskey, BADGES))
    texts = parse_texts(read_source(args.misskey, LOCALE))

    entries = []
    for name, badge in badges.items():
        text = texts.get(name) or sys.exit(f"no text for {name}")
        flavor = swift_string(text["flavor"]) if "flavor" in text else "nil"
        background = f"({', '.join(badge['background'])})" if badge["background"] else "nil"
        entries.append(
            f'        "{name}": Achievement(\n'
            f'            title: {swift_string(text["title"])},\n'
            f'            description: {swift_string(text["description"])},\n'
            f'            flavor: {flavor},\n'
            f'            emoji: "{badge["emoji"]}", background: {background}, frame: .{badge["frame"]}),\n')

    OUTPUT.write_text(
        f"// Generated by scripts/gen_achievements.py from Misskey {version}. Do not edit.\n"
        "\n"
        "extension Achievement {\n"
        "    static let catalog: [String: Achievement] = [\n"
        + "".join(entries)
        + "    ]\n"
        "}\n",
        encoding="utf-8")
    print(f"{len(entries)} achievements from Misskey {version} -> {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
